<a href="https://colab.research.google.com/github/ytucayasi/actividad-U02-S01/blob/main/Actividad_Unidad_2_Sesi%C3%B3n_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Importa la biblioteca NumPy en tu entorno de trabajo de Python utilizando la siguiente instrucción:


In [8]:
import numpy as np

#1. Creación de Arrays

##1.1 Crea un array unidimensional (vector) con 5 elementos enteros de tu elección.


In [5]:
# Crea un arreglo unidimensional con los números del 1 al 5
array_unidimensional = np.array([1, 2, 3, 4, 5])

# Imprime el arreglo creado
print(array_unidimensional)

[1 2 3 4 5]


##1.2 Crea una matriz bidimensional (matriz) de tamaño 3x3 con valores enteros consecutivos.

In [79]:
# Crea un arreglo bidimensional (matriz) con 3 filas y 3 columnas
# Cada fila contiene una lista de números
array_bidimensional = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Imprime la matriz bidimensional creada
print(array_bidimensional)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


##1.3 Utiliza la función np.zeros() para crear una matriz de tamaño 2x4 llena de ceros

In [78]:
# Crea un arreglo bidimensional (matriz) de 2 filas y 4 columnas, lleno de ceros.
# El argumento 'int' especifica que los ceros serán del tipo entero.
array_ceros = np.zeros((2, 4), int)

# Imprime la matriz de ceros creada
print(array_ceros)

[[0 0 0 0]
 [0 0 0 0]]


##1.4 Utiliza la función np.ones() para crear una matriz de tamaño 3x2 llena de unos

In [17]:
# Creamos un array de unos con dimensiones 3x2 utilizando NumPy
array_unos = np.ones((3, 2), int)

# Imprimimos el array de unos
print(array_unos)

[[1 1]
 [1 1]
 [1 1]]


##1.5 Utiliza la función np.random.randint() para crear una matriz de tamaño 4x4 con números enteros aleatorios entre 0 y 10

In [80]:
# Generamos una matriz de enteros aleatorios entre 0 y 9 (inclusive) con dimensiones 4x4 utilizando NumPy
array_randint = np.random.randint(0, 10, size=(4, 4))

# Imprimimos la matriz de enteros aleatorios
print(array_randint)

[[4 6 9 2]
 [6 4 1 5]
 [6 0 1 3]
 [1 2 2 3]]


# 2. Acceso a elementos

## 2.1. Accede al tercer elemento del vector creado en el paso 1.

In [27]:
print("El tercer elemento del vector creado en el paso 1: ", array_unidimensional[2])

El tercer elemento del vector creado en el paso 1:  3


##2.2. Accede al elemento en la segunda fila y segunda columna de la matriz creada en el paso 2.

In [26]:
print("El elemento en la segunda fila y segunda columna de la matriz creada en el paso 2: ", array_bidimensional[1][1])

El elemento en la segunda fila y segunda columna de la matriz creada en el paso 2:  5


#3. Propiedades de los Arrays

##3.1. Utiliza el atributo ndim para verificar la cantidad de dimensiones de la matriz creada en el paso 2.

In [29]:
print("La cantidad de dimensiones de la matriz creada en el paso 2 es: ", array_bidimensional.ndim, "dimensiones")

La cantidad de dimensiones de la matriz creada en el paso 2 es:  2 dimensiones


##3.2. Utiliza el atributo shape para obtener la forma de la matriz creada en el paso 2.

In [33]:
print("La forma de la matriz creada en el paso 2, tiene", array_bidimensional.shape[0], "filas", "y", array_bidimensional.shape[1], "columnas")

La forma de la matriz creada en el paso 2, tiene 3 filas y 3 columnas


##3.3. Utiliza el atributo size para obtener el tamaño total de la matriz creada en el paso 2.

In [36]:
print("El tamaño de la matriz creada en el paso 2 es:", array_bidimensional.size, "elementos")

El tamaño de la matriz creada en el paso 2 es: 9 elementos


#4. Operaciones Básicas

##4.1. Suma dos matrices de tamaño 2x2 con valores aleatorios entre 0 y 10

In [41]:
a = np.random.randint(0, 10, size=(2, 2))
b = np.random.randint(0, 10, size=(2, 2))
c = a + b
print("Matriz 1: ")
print(a)
print("Matriz 2: ")
print(b)
print("Suma de la Matriz 1 y 2: ")
print(c)

Matriz 1: 
[[1 0]
 [6 1]]
Matriz 2: 
[[8 4]
 [9 3]]
Suma de la Matriz 1 y 2: 
[[ 9  4]
 [15  4]]


##4.2. Multiplica dos matrices de tamaño 3x2 y 2x3 respectivamente.

In [61]:
d = np.random.randint(0, 10, size=(3, 3))
e = np.random.randint(0, 10, size=(3, 3))
f = d * e
print("Matriz 1")
print(d)
print("Matriz 2")
print(e)
print("Multiplicación de la Matriz 1 y 2")
print(f)

Matriz 1
[[4 1 1]
 [7 1 3]
 [5 8 8]]
Matriz 2
[[9 6 7]
 [5 0 8]
 [3 0 7]]
Multiplicación de la Matriz 1 y 2
[[36  6  7]
 [35  0 24]
 [15  0 56]]


##4.3. Divide una matriz de tamaño 2x2 por otra matriz de tamaño 2x2, utilizando tanto la división por elementos como la multiplicación por la inversa.


In [54]:
g = np.random.randint(1, 10, size=(2, 2))
h = np.random.randint(1, 10, size=(2, 2))
i = g / h
h_inversa = np.linalg.inv(h)
j = np.dot(g, h_inversa)
print("Matriz 1")
print(g)
print("Matriz 2")
print(h)
print("División de la Matriz 1 y 2")
print(i)
print("Multiplicación por la inversa de la Matriz 2:")
print(j)

Matriz 1
[[2 8]
 [2 1]]
Matriz 2
[[7 7]
 [1 9]]
División de la Matriz 1 y 2
[[0.28571429 1.14285714]
 [2.         0.11111111]]
Multiplicación por la inversa de la Matriz 2:
[[ 0.17857143  0.75      ]
 [ 0.30357143 -0.125     ]]


#5. Manipulación de Arrays

##5.1. Utiliza la función reshape() para convertir el vector creado en el paso 2 en una matriz de tamaño 1x9.

In [62]:
print("Trasformar la forma de la matriz creada en el paso 2")
print(array_bidimensional.reshape(1, 9))

Trasformar la forma de la matriz creada en el paso 2
[[1 2 3 4 5 6 7 8 9]]


## 5.2. Utiliza la función flatten() para convertir la matriz creada en el paso 2 en un vector unidimensional.

In [65]:
print("Transformando la matriz creada en el paso 2 en una matriz unidimensional")
print(array_bidimensional.flatten())

Transformando la matriz creada en el paso 2 en una matriz unidimensional
[1 2 3 4 5 6 7 8 9]


#6. Operaciones Estadísticas

##6.1. Calcula la suma de todos los elementos de la matriz creada en el paso 2.

In [66]:
suma = 0
for i in range(3):
  for j in range(3):
    suma += array_bidimensional[i][j]
print("La suma de todos los elementos de la matriz creada en el paso 2:", suma)

La suma de todos los elementos de la matriz creada en el paso 2: 45


##6.2. Calcula la media de cada fila de la matriz creada en el paso 2.


In [69]:
promedio = 0
conteo = 0
total = 0
for i in range(3):
  promedio = 0
  conteo = 0
  for j in range(3):
    promedio += array_bidimensional[i][j]
    conteo += 1
  total = promedio / conteo
  print("El promedio de la fila",(i + 1), "es:", total)

El promedio de la fila 1 es: 2.0
El promedio de la fila 2 es: 5.0
El promedio de la fila 3 es: 8.0


#7. Indexación y Rebanado

##7.1. Imprime la primera fila de la matriz creada en el paso 2.

In [70]:
print("Mostrando la primera fila de la matriz creada en el paso 2")
print(array_bidimensional[0])

Mostrando la primera fila de a matriz creada en el paso 2
[1 2 3]


##7.2. Imprime las primeras dos columnas de la matriz creada en el paso 2.

In [71]:
print("Mostrando las primeras 2 columnas de la matriz creada en el paso 2")
print(array_bidimensional[0][:2])

Mostrando las primeras 2 columnas de la matriz creada en el paso 2
[1 2]


#8. Ejercicio Adicional

##8.1. Define una matriz de tamaño 4x4 con valores aleatorios.

In [74]:
matriz_adicional = np.random.randint(1, 100, size=(4, 4))
print(matriz_adicional)

[[ 1 64 98 60]
 [25 67 44 39]
 [55 74 53  8]
 [28 12 51 93]]


##8.2. Escribe un código para encontrar el valor máximo y mínimo de la matriz, así como su posición.

In [77]:
# Definición de la función encontrar_max_min que recibe una matriz como entrada
def encontrar_max_min(matriz):
    # Inicialización de las variables para almacenar el máximo y mínimo valores
    max_valor = float('-inf')  # Se inicializa con el valor negativo infinito
    min_valor = float('inf')   # Se inicializa con el valor positivo infinito
    # Inicialización de las variables para almacenar las posiciones del máximo y mínimo valores
    max_posicion = None  # Inicialmente no se ha encontrado ninguna posición del máximo valor
    min_posicion = None  # Inicialmente no se ha encontrado ninguna posición del mínimo valor
    # Iteración sobre las filas de la matriz
    for i in range(len(matriz)):
        # Iteración sobre las columnas de la matriz
        for j in range(len(matriz[0])):
            # Comprobación si el valor actual es mayor que el máximo valor encontrado hasta ahora
            if matriz[i][j] > max_valor:
                # Si es así, actualiza el máximo valor y su posición
                max_valor = matriz[i][j]
                max_posicion = (i, j)
            # Comprobación si el valor actual es menor que el mínimo valor encontrado hasta ahora
            if matriz[i][j] < min_valor:
                # Si es así, actualiza el mínimo valor y su posición
                min_valor = matriz[i][j]
                min_posicion = (i, j)

    # Retorna el máximo valor, su posición, el mínimo valor y su posición
    return max_valor, max_posicion, min_valor, min_posicion

# Llamada a la función encontrar_max_min con la matriz_adicional como argumento
maximo, posicion_max, minimo, posicion_min = encontrar_max_min(matriz_adicional)

# Impresión del máximo valor y su posición
print("El valor máximo es:", maximo, "en la posición:", posicion_max)

# Impresión del mínimo valor y su posición
print("El valor mínimo es:", minimo, "en la posición:", posicion_min)

El valor máximo es: 98 en la posición: (0, 2)
El valor mínimo es: 1 en la posición: (0, 0)
